[package]
name = "yarn-spinner"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.2"
prost = "0.11"
rand = "0.8.5"
thiserror = "1.0"

[dev-dependencies]
dialoguer = "0.10.3"


[build-dependencies]
prost-build = "0.11.8"
